title: Project

files: false

pages: Datapoint

fields:
  title:
    label: Title
    type:  text

  nav_title:
    label: Menu Title
    type: text

  heading_1:
    label: Heading
    type: textarea

  normal_text:
    label: Text block
    type: textarea

  heading_2:
    label: Bold Text at the end
    type: textarea
